export const REQUEST_FETCH_TODOS = 'REQUEST:FETCH:TODOS'

export const RECEIVE_FETCH_TODOS = 'RECEIVE:FETCH:TODOS'

export const REQUEST_TODOS_FAILED = 'REQUEST:FAILED:TODOS'

export const REQUEST_UPDATE_TODO = 'REQUEST:UPDATE:TODO'

export const REQUEST_CREATE_TODO = 'REQUEST:CREATE:TODO'

export const REQUEST_REMOVE_TODO = 'REQUEST:REMOVE:TODO'

export const REQUEST_COMPLETE_TODO = 'REQUEST:COMPLETE:TODO'

export const REQUEST_EDIT_TODO = 'REQUEST:EDIT:TODO'